name: Enforce repository settings just once

on: [push]

jobs:
  probot-settings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run probot-settings
        uses: elstudio/actions-settings@v2
